import { randomBytes, randomUUID, timingSafeEqual } from 'node:crypto';
import type { OperatorIdentity } from './OperatorIdentityService.js';
import { OperatorIdentityService } from './OperatorIdentityService.js';
import { InMemorySecureDashboardStore, type SecureDashboardStore } from './EncryptedDashboardSessionStore.js';

export interface DashboardSession { sessionId:string; csrfToken:string; identity:OperatorIdentity; expiresAt:Date; }
export class OperatorDashboardSessionService {
  constructor(private readonly identities:OperatorIdentityService,private readonly ttlMinutes:number,private readonly clock:()=>Date=()=>new Date(),private readonly store:SecureDashboardStore=new InMemorySecureDashboardStore()){}
  async create(token:string):Promise<DashboardSession|undefined>{const identity=this.identities.authenticate(token);if(!identity)return undefined;return this.createForIdentity(identity);}
  async createForIdentity(identity:OperatorIdentity,authMethod:'local'|'oidc'='local'):Promise<DashboardSession>{const sessionId=randomUUID();const csrfToken=randomBytes(32).toString('base64url');const ttl=new Date(this.clock().getTime()+this.ttlMinutes*60000);const expiresAt=identity.expiresAt&&identity.expiresAt<ttl?identity.expiresAt:ttl;await this.store.put(sessionId,{kind:'session',payload:{operatorId:identity.id,csrfToken,roles:identity.roles,authMethod},expiresAt});return{sessionId,csrfToken,identity,expiresAt};}
  async get(sessionId:string|undefined):Promise<DashboardSession|undefined>{if(!sessionId)return undefined;const value=await this.store.get(sessionId,'session');if(!value)return undefined;const operatorId=String(value.payload.operatorId??''),csrfToken=String(value.payload.csrfToken??''),authMethod=String(value.payload.authMethod??'local');const local=this.identities.findActive(operatorId);const roles=Array.isArray(value.payload.roles)?value.payload.roles.filter((x):x is OperatorIdentity['roles'][number]=>['viewer','operator','admin'].includes(String(x))):[];const identity=authMethod==='oidc'&&roles.length?{id:operatorId,tokenSha256:'',roles,expiresAt:value.expiresAt,revoked:false}:local;if(value.expiresAt<=this.clock()||!identity){await this.store.delete(sessionId);return undefined;}return{sessionId,csrfToken,identity,expiresAt:value.expiresAt};}
  verifyCsrf(session:DashboardSession,supplied:string|undefined):boolean{if(!supplied)return false;const a=Buffer.from(session.csrfToken);const b=Buffer.from(supplied);return a.length===b.length&&timingSafeEqual(a,b);}
  async destroy(sessionId:string|undefined):Promise<void>{if(sessionId)await this.store.delete(sessionId);}
  async createLoginChallenge(){const id=randomUUID();const csrfToken=randomBytes(32).toString('base64url'),expiresAt=new Date(this.clock().getTime()+300000);await this.store.put(id,{kind:'login_challenge',payload:{csrfToken},expiresAt});return{id,csrfToken};}
  async consumeLoginChallenge(id:string|undefined,supplied:string|undefined):Promise<boolean>{if(!id||!supplied)return false;const value=await this.store.get(id,'login_challenge');await this.store.delete(id);if(!value||value.expiresAt<=this.clock())return false;const a=Buffer.from(String(value.payload.csrfToken??'')),b=Buffer.from(supplied);return a.length===b.length&&timingSafeEqual(a,b);}
}
